port: /dev/cu.usbserial-FTAAMLDU
version: 0.2.1
baudrate: 3000000
max_current: 400
type: right
control_mode: current_based_position
motor_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
joint_ids:
- thumb_mcp
- thumb_abd
- thumb_pip
- thumb_dip
- index_abd
- index_mcp
- index_pip
- middle_abd
- middle_mcp
- middle_pip
- ring_abd
- ring_mcp
- ring_pip
- pinky_abd
- pinky_mcp
- pinky_pip
- wrist
joint_to_motor_map:
  thumb_mcp: -4
  thumb_abd: -3
  thumb_pip: -1
  thumb_dip: -2
  index_abd: 14
  index_mcp: -15
  index_pip: -16
  middle_abd: 13
  middle_mcp: -8
  middle_pip: -9
  ring_abd: -5
  ring_mcp: -7
  ring_pip: -6
  pinky_abd: 12
  pinky_mcp: -10
  pinky_pip: -11
  wrist: -17
joint_roms:
  thumb_mcp:
  - -50
  - 50
  thumb_abd:
  - -20
  - 42
  thumb_pip:
  - -12
  - 108
  thumb_dip:
  - -20
  - 112
  index_abd:
  - -37
  - 37
  index_mcp:
  - -20
  - 95
  index_pip:
  - -20
  - 108
  middle_abd:
  - -37
  - 37
  middle_mcp:
  - -20
  - 91
  middle_pip:
  - -20
  - 107
  ring_abd:
  - -37
  - 37
  ring_mcp:
  - -20
  - 91
  ring_pip:
  - -20
  - 107
  pinky_abd:
  - -37
  - 37
  pinky_mcp:
  - -20
  - 98
  pinky_pip:
  - -20
  - 108
  wrist:
  - -50
  - 30
neutral_position:
  thumb_mcp: -13
  thumb_abd: 43
  thumb_pip: 33
  thumb_dip: 19
  index_abd: 25
  index_mcp: 0
  index_pip: 0
  middle_abd: -2
  middle_mcp: 0
  middle_pip: 0
  ring_abd: -20
  ring_mcp: -1
  ring_pip: 0
  pinky_abd: -55
  pinky_mcp: 1
  pinky_pip: 0
  wrist: 0
calibration_current: 350
calibration_step_size: 0.1
calibration_step_period: 0.001
calibration_num_stable: 10
calibration_threshold: 0.01
calibration_sequence:
- step: 1
  joints:
    thumb_mcp: flex
- step: 2
  joints:
    thumb_mcp: extend
- step: 3
  joints:
    thumb_abd: flex
- step: 4
  joints:
    thumb_abd: extend
