/**
 * DexSlide Firmware — Main
 *
 * STM32F103RCT6
 * Reads 20 joint angles from 5x ADS1115 over two I2C buses,
 * streams data over USB CDC, and displays on debug LCD.
 */

#include "main.h"
#include "ads1115.h"
#include "usb_comm.h"
#include "lcd_driver.h"

/* ---- Peripheral Handles ---- */
I2C_HandleTypeDef hi2c1;
I2C_HandleTypeDef hi2c2;

/* ---- ADC Handles ---- */
// I2C1 bus: Thumb, Index, Middle
ADS1115_Handle adc_thumb  = { .hi2c = &hi2c1, .addr = ADS1115_ADDR_GND };
ADS1115_Handle adc_index  = { .hi2c = &hi2c1, .addr = ADS1115_ADDR_VDD };
ADS1115_Handle adc_middle = { .hi2c = &hi2c1, .addr = ADS1115_ADDR_SDA };

// I2C2 bus: Ring, Pinky
ADS1115_Handle adc_ring   = { .hi2c = &hi2c2, .addr = ADS1115_ADDR_GND };
ADS1115_Handle adc_pinky  = { .hi2c = &hi2c2, .addr = ADS1115_ADDR_VDD };

/* ---- Joint Angle Storage ---- */
uint16_t joint_angles[TOTAL_JOINTS] = {0};

/* ---- Private Function Prototypes ---- */
static void MX_I2C1_Init(void);
static void MX_I2C2_Init(void);
static void MX_GPIO_Init(void);
static void ReadAllJoints(void);

/* ---- Main ---- */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_I2C2_Init();

    // TODO: MX_USB_DEVICE_Init() — requires USB middleware (CubeMX generates this)
    USB_Comm_Init();

    LCD_Init();

    // Verify ADC communication
    ADS1115_Init(&adc_thumb);
    ADS1115_Init(&adc_index);
    ADS1115_Init(&adc_middle);
    ADS1115_Init(&adc_ring);
    ADS1115_Init(&adc_pinky);

    /* ---- Main Loop ---- */
    uint32_t lcd_update_tick = 0;

    while (1)
    {
        // 1. Read all 20 joints
        ReadAllJoints();

        // 2. Send over USB
        USB_Comm_PackAndSend(joint_angles);

        // 3. Update LCD at lower rate (~10 Hz)
        if (HAL_GetTick() - lcd_update_tick >= 100)
        {
            lcd_update_tick = HAL_GetTick();
            LCD_DisplayJoints(joint_angles);
        }
    }
}

/**
 * Read all 20 joints from 5 ADCs.
 * Sequential polling: read 4 channels from each ADC.
 */
static void ReadAllJoints(void)
{
    int16_t raw[4];

    // I2C1 bus — can interleave with I2C2 if using DMA later
    if (ADS1115_ReadAllChannels(&adc_thumb, raw) == HAL_OK) {
        for (int i = 0; i < 4; i++) joint_angles[0 + i] = (uint16_t)raw[i];
    }
    if (ADS1115_ReadAllChannels(&adc_index, raw) == HAL_OK) {
        for (int i = 0; i < 4; i++) joint_angles[4 + i] = (uint16_t)raw[i];
    }
    if (ADS1115_ReadAllChannels(&adc_middle, raw) == HAL_OK) {
        for (int i = 0; i < 4; i++) joint_angles[8 + i] = (uint16_t)raw[i];
    }

    // I2C2 bus
    if (ADS1115_ReadAllChannels(&adc_ring, raw) == HAL_OK) {
        for (int i = 0; i < 4; i++) joint_angles[12 + i] = (uint16_t)raw[i];
    }
    if (ADS1115_ReadAllChannels(&adc_pinky, raw) == HAL_OK) {
        for (int i = 0; i < 4; i++) joint_angles[16 + i] = (uint16_t)raw[i];
    }
}

/* ---- I2C1 Init: 400kHz Fast Mode ---- */
static void MX_I2C1_Init(void)
{
    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = 400000;
    hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1 = 0;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) {
        Error_Handler();
    }
}

/* ---- I2C2 Init: 400kHz Fast Mode ---- */
static void MX_I2C2_Init(void)
{
    hi2c2.Instance = I2C2;
    hi2c2.Init.ClockSpeed = 400000;
    hi2c2.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c2.Init.OwnAddress1 = 0;
    hi2c2.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c2.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c2.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c2.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c2) != HAL_OK) {
        Error_Handler();
    }
}

/* ---- GPIO Init (minimal) ---- */
static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    // I2C GPIO config is handled by HAL_I2C_MspInit in stm32f1xx_hal_msp.c
}

/* ---- System Clock Config ---- */
void SystemClock_Config(void)
{
    // TODO: Configure for 72MHz using HSE 8MHz + PLL
    // This is typically generated by STM32CubeMX.
    // Placeholder — fill in after CubeMX project generation.

    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;  // 8MHz * 9 = 72MHz
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler();
    }

    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;   // 36MHz max for APB1
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;   // 72MHz
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
        Error_Handler();
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}
