/**
 * USB CDC Communication
 *
 * Packs joint angle data into a frame and sends over USB Virtual COM Port.
 * Depends on STM32 USB Device middleware (generated by CubeMX).
 */

#include "usb_comm.h"

// TODO: Include the CubeMX-generated USB CDC header
// #include "usbd_cdc_if.h"

void USB_Comm_Init(void)
{
    // USB CDC initialization is handled by MX_USB_DEVICE_Init()
    // generated by CubeMX. This function is a placeholder for any
    // additional application-level setup.
}

/**
 * Compute simple XOR checksum over the angle data.
 */
static uint8_t compute_checksum(const uint16_t *data, uint8_t count)
{
    uint8_t cs = 0;
    const uint8_t *bytes = (const uint8_t *)data;
    for (uint16_t i = 0; i < count * 2; i++) {
        cs ^= bytes[i];
    }
    return cs;
}

int USB_Comm_SendFrame(const JointDataFrame *frame)
{
    // TODO: Replace with actual USB CDC transmit call:
    // uint8_t result = CDC_Transmit_FS((uint8_t *)frame, FRAME_SIZE);
    // return (result == USBD_OK) ? 0 : -1;

    (void)frame;  // suppress unused warning until USB middleware is added
    return -1;
}

int USB_Comm_PackAndSend(const uint16_t angles[TOTAL_JOINTS])
{
    JointDataFrame frame;
    frame.header = FRAME_HEADER;

    for (int i = 0; i < TOTAL_JOINTS; i++) {
        frame.angles[i] = angles[i];
    }

    frame.checksum = compute_checksum(frame.angles, TOTAL_JOINTS);
    frame.tail = 0x0D;

    return USB_Comm_SendFrame(&frame);
}
