"""
Type hints for jkrc module - JAKA Robot Python SDK
"""

from typing import Tuple, Optional, Union

# Enumerations
class CoordType:
    COORD_BASE: int
    COORD_JOINT: int
    COORD_TOOL: int

class MoveMode:
    ABS: int
    INCR: int
    CONTINUE: int
    STOP: int

# Main Robot Control Class
class RC:
    """
    Robot control class for JAKA robots.
    """
    def __init__(self, ip_addr: str) -> None: ...
    
    # Connection methods
    def log_in(self, use_grpc: int = 0) -> Tuple[int]: ...
    def log_out(self) -> Tuple[int]: ...
    
    # Basic control methods
    def power_on(self) -> Tuple[int]: ...
    def power_off(self) -> Tuple[int]: ...
    def shut_down(self) -> Tuple[int]: ...
    def enable_robot(self) -> Tuple[int]: ...
    def disable_robot(self) -> Tuple[int]: ...
    
    # Motion methods
    def jog(self, aj_num: int, move_mode: MoveMode, coord_type: CoordType, jog_vel: float, pos_cmd: float = 0) -> Tuple[int]: ...
    def jog_stop(self, jnum: int) -> Tuple[int]: ...
    
    def joint_move(self, joint_pos: Tuple[float, float, float, float, float, float], 
                   move_mode: MoveMode, is_block: bool, speed: float) -> Tuple[int]: ...
                   
    def linear_move(self, end_pos: Tuple[float, float, float, float, float, float], 
                    move_mode: MoveMode, is_block: bool, speed: float) -> Tuple[int]: ...
                    
    def circular_move(self, end_pos: Tuple[float, float, float, float, float, float], 
                      mid_pos: Tuple[float, float, float, float, float, float], 
                      move_mode: MoveMode, is_block: bool, speed: float, acc: float, tol: float) -> Tuple[int]: ...
    
    # Extended motion methods
    def joint_move_extend(self, joint_pos: Tuple[float, float, float, float, float, float], 
                          move_mode: MoveMode, is_block: bool, speed: float, acc: float, tol: float) -> Tuple[int]: ...
                          
    def linear_move_extend(self, end_pos: Tuple[float, float, float, float, float, float], 
                           move_mode: MoveMode, is_block: bool, speed: float, acc: float, tol: float) -> Tuple[int]: ...
                           
    def linear_move_extend_ori(self, end_pos: Tuple[float, float, float, float, float, float], 
                               move_mode: MoveMode, is_block: bool, speed: float, acc: float, tol: float, 
                               ori_vel: float = 3.1415926535897932384626433832795, 
                               ori_acc: float = 12.566370614359172) -> Tuple[int]: ...
    
    # Servo methods
    def servo_move_enable(
        self, 
        enable: bool, 
        is_block: bool = True, 
        robot_id: int = 0
    ) -> Tuple[int]: ...
    def is_in_servomove(self) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def servo_j(self, joint_pos: Tuple[float, float, float, float, float, float], 
                move_mode: MoveMode, step_num: int) -> Tuple[int]: ...
    def servo_p(self, end_pos: Tuple[float, float, float, float, float, float], 
                move_mode: MoveMode, step_num: int) -> Tuple[int]: ...
    
    # EDG servo methods
    def edg_servo_p(self, end_pos: Tuple[float, float, float, float, float, float], 
                    move_mode: MoveMode, step_num: int, robot_index: int) -> Tuple[int]: ...
    def edg_servo_j(self, joint_pos: Tuple[float, float, float, float, float, float], 
                    move_mode: MoveMode, step_num: int, robot_index: int) -> Tuple[int]: ...
    def edg_init(self, en: bool, edg_stat_ip: str) -> Tuple[int]: ...
    def edg_init_extend(self, en: bool, edg_stat_ip: str, edg_port: int, edg_mode: int) -> Tuple[int]: ...
    
    # Servo filter methods
    def servo_move_use_none_filter(self) -> Tuple[int]: ...
    def servo_move_use_joint_LPF(self, cutoffFreq: float) -> Tuple[int]: ...
    def servo_move_use_joint_NLF(self, max_vr: float, max_ar: float, max_jr: float) -> Tuple[int]: ...
    def servo_move_use_carte_NLF(self, max_vp: float, max_ap: float, max_jp: float, 
                                 max_vr: float, max_ar: float, max_jr: float) -> Tuple[int]: ...
    
    # Getter methods
    def get_joint_position(self) -> Union[Tuple[int], Tuple[int, Tuple[float, float, float, float, float, float]]]: ...
    def get_tcp_position(self) -> Union[Tuple[int], Tuple[int, Tuple[float, float, float, float, float, float]]]: ...
    def get_actual_joint_position(self) -> Union[Tuple[int], Tuple[int, Tuple[float, float, float, float, float, float]]]: ...
    def get_actual_tcp_position(self) -> Union[Tuple[int], Tuple[int, Tuple[float, float, float, float, float, float]]]: ...
    
    # Error handling
    def get_last_error(self) -> Tuple[int]: ...
    def set_error_handler(self, func) -> Tuple[int]: ...
    
    # IO methods
    def get_digital_input(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def get_digital_output(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, bool]]: ...
    def set_digital_output(self, type: int, index: int, value: bool) -> Tuple[int]: ...
    def get_analog_input(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, float]]: ...
    def get_analog_output(self, type: int, index: int) -> Union[Tuple[int], Tuple[int, float]]: ...
    def set_analog_output(self, type: int, index: int, value: float) -> Tuple[int]: ...
    
    # Program methods
    def program_load(self, file_name: str) -> Tuple[int]: ...
    def program_run(self) -> Tuple[int]: ...
    def program_pause(self) -> Tuple[int]: ...
    def program_resume(self) -> Tuple[int]: ...
    def program_abort(self) -> Tuple[int]: ...
    
    # Tool methods
    def get_tool_id(self) -> Union[Tuple[int], Tuple[int, int]]: ...
    def set_tool_id(self, id: int) -> Tuple[int]: ...
    
    # Version methods
    def get_sdk_version(self) -> Union[Tuple[int], Tuple[int, Tuple[int, int, int, int]]]: ...
    
    # Properties
    ip_addr: str
    handle: int