port: /dev/cu.usbmodem3101
version: 0.2.1
baudrate: 1000000
max_current: 300
type: left
control_mode: current_based_position
motor_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
joint_ids:
- wrist
- thumb_cmc
- thumb_abd
- thumb_mcp
- thumb_dip
- index_abd
- index_mcp
- index_pip
- middle_abd
- middle_mcp
- middle_pip
- ring_abd
- ring_mcp
- ring_pip
- pinky_abd
- pinky_mcp
- pinky_pip
joint_to_motor_map:
  thumb_cmc: -10
  thumb_abd: -13
  thumb_mcp: 12
  thumb_dip: 11
  index_abd: -7
  index_mcp: -8
  index_pip: -9
  middle_abd: -6
  middle_mcp: -17
  middle_pip: -2
  ring_abd: -5
  ring_mcp: 4
  ring_pip: -3
  pinky_abd: 14
  pinky_mcp: -15
  pinky_pip: 16
  wrist: -1
joint_roms:
  wrist:
  - -65
  - 35
  thumb_cmc:
  - -45
  - 33
  thumb_abd:
  - -18
  - 55
  thumb_mcp:
  - -25
  - 100
  thumb_dip:
  - -15
  - 107
  index_abd:
  - -30
  - 25
  index_mcp:
  - -25
  - 100
  index_pip:
  - -15
  - 107
  middle_abd:
  - -27
  - 27
  middle_mcp:
  - -25
  - 100
  middle_pip:
  - -15
  - 107
  ring_abd:
  - -27
  - 27
  ring_mcp:
  - -25
  - 100
  ring_pip:
  - -15
  - 107
  pinky_abd:
  - -30
  - 30
  pinky_mcp:
  - -25
  - 100
  pinky_pip:
  - -15
  - 107
neutral_position:
  thumb_cmc: 0
  thumb_abd: 50
  thumb_mcp: 33
  thumb_dip: 18
  index_abd: -14
  index_mcp: 2
  index_pip: 6
  middle_abd: -4
  middle_mcp: 2
  middle_pip: 4
  ring_abd: 10
  ring_mcp: -2
  ring_pip: 8
  pinky_abd: 22
  pinky_mcp: -4
  pinky_pip: -2
  wrist: -20
calibration_current: 300
calibration_step_size: 0.15
calibration_step_period: 0.0001
calibration_num_stable: 10
calibration_threshold: 0.01
calibration_sequence:
- step: 1
  joints:
    thumb_cmc: flex
- step: 2
  joints:
    thumb_cmc: extend
- step: 3
  joints:
    thumb_abd: flex
- step: 4
  joints:
    thumb_abd: extend
- step: 5
  joints:
    thumb_mcp: flex
- step: 6
  joints:
    thumb_mcp: extend
- step: 7
  joints:
    thumb_dip: flex
- step: 8
  joints:
    thumb_dip: extend
- step: 9
  joints:
    index_abd: flex
    middle_abd: flex
    ring_abd: flex
    pinky_abd: flex
- step: 10
  joints:
    index_abd: extend
    middle_abd: extend
    ring_abd: extend
    pinky_abd: extend
- step: 11
  joints:
    index_mcp: flex
    middle_mcp: flex
    ring_mcp: flex
    pinky_mcp: flex
- step: 12
  joints:
    index_mcp: extend
    middle_mcp: extend
    ring_mcp: extend
    pinky_mcp: extend
- step: 13
  joints:
    index_pip: flex
    middle_pip: flex
    ring_pip: flex
    pinky_pip: flex
- step: 14
  joints:
    index_pip: extend
    middle_pip: extend
    ring_pip: extend
    pinky_pip: extend
- step: 15
  joints:
    wrist: flex
- step: 16
  joints:
    wrist: extend
sensors:
  finger_to_sensor_id:
    thumb: 2
    index: 4
    middle: 0
    ring: 1
    pinky: 3